[rte] Allow to modify style of core-blocks
vivid-planet/comet-admin pull request #194
Opened 2020-08-27 07:07 UTC by rabengraph

2020-08-27 10:44 UTC, jamesricky requested changes

2020-08-27 10:44 UTC, jamesricky commented on packages/react-admin-rte/src/core/Controls/useBlockTypes.ts
> +        name: "unstyled",
Ich finde, dass sollte dan auch `standard` oder `default` heißen, nachdem es ja schon gestyled werden kann/soll.

2020-08-27 13:03 UTC, rabengraph commented on packages/react-admin-rte/src/core/Controls/useBlockTypes.ts
> +        name: "unstyled",
Das ist der Name für den standard-block-type von draftjs. Der Name ist von draft-js so vorgegeben: zB hier https://github.com/facebook/draft-js/blob/d47bc2f5814134fbebe34233e8f7030007d48b1b/src/model/immutable/ContentState.js#L226

... "unstyled" ist wirklich nicht sehr geglückt als Name, aber den bekommen wir nicht weg.

2020-08-28 09:41 UTC, jamesricky approved these changes

2020-09-12 08:36 UTC, nsams commented on packages/react-admin-rte/src/core/types.ts
> +    [key: string]: ICoreBlockType;
könnten da nicht alle keys der core blocks aufgelistet sein?

2020-09-14 08:21 UTC, rabengraph commented on packages/react-admin-rte/src/core/types.ts
> +    [key: string]: ICoreBlockType;
Ja!

2020-09-17 17:12 UTC, nsams reviewed
warum eigentlich die aufteilung in core und custom? wäre nicht eine map ausreichend und einfacher?

2020-09-30 06:56 UTC, rabengraph commented
> warum eigentlich die aufteilung in core und custom? wäre nicht eine map ausreichend und einfacher?

coreBlockTypeMap und customBlockTypeMap haben unterschiedliche Funktionen, bei coreBlockTypeMap kann man das styling für die core-blocks festlegen, registriert werden die core-blocks aber über das supports-prop.
Mit customBlockTypeMap hingegen registriert man custom blocks, deswegen ist hier auch die Angabe eines "labels" verpflichtend.

Und, man kann den misch-typ der rauskommen würde nicht typisieren:
[https://stackoverflow.com/questions/64115221/can-a-string-literal-type-and-type-string-be-mixed-and-used-as-key-in-a-mapped](https://stackoverflow.com/questions/64115221/can-a-string-literal-type-and-type-string-be-mixed-and-used-as-key-in-a-mapped)

... Ich glaub die API vom RTE ist an sich da nicht ganz ideal, ich versuch noch was anderes.

2020-12-30 13:24 UTC, rabengraph commented
alternative: https://github.com/vivid-planet/comet-admin/pull/273

2020-12-30 13:24 UTC, closed without merging