Pagination
vivid-planet/comet-admin pull request #197
Opened 2020-09-14 09:56 UTC by Feetscha

<img width="807" alt="Bildschirmfoto 2020-09-14 um 11 43 07" src="https://user-images.githubusercontent.com/17086832/93071099-f7639700-f67f-11ea-9523-fad6c0f092a7.png">
<img width="1401" alt="Bildschirmfoto 2020-09-14 um 11 48 26" src="https://user-images.githubusercontent.com/17086832/93071376-60e3a580-f680-11ea-9da5-68aefb344eeb.png">

2020-09-16 04:56 UTC, Feetscha commented
Motivation für den Merge Request ist eine Anforderung aus Mobidrome Cockpit.

2020-09-16 15:52 UTC, nsams requested changes
bitte .DS_Store löschen

2020-09-16 15:52 UTC, nsams commented on packages/react-admin-core/src/table/Pagination.sc.ts
> +        text-align: center;
@jamesricky bitte um review von dem styling

2020-09-16 15:52 UTC, nsams commented on packages/react-admin-core/src/table/Pagination.tsx
> +    const [lastInteraction, setLastInteraction] = React.useState<"input" | "button" | undefined>();
das geht besser: ier heraussen verwende nur den akuell gültigen wert, im PageInput mach eine lokale kopie (in einem local state) von dem input value.

2020-09-16 15:52 UTC, nsams commented on packages/react-admin-core/src/table/Pagination.tsx
> +            <Form onSubmit={onSubmit} initialValues={{ page: 1 }}>
so ein simples input ist das overkill. Noch dazu submittest du sie ja gar nie.

2020-09-16 15:52 UTC, nsams commented on packages/react-admin-core/src/table/paging/IPagingInfo.ts
> +    hideTotalCount?: boolean;
hideTotalCount gehört nicht da dazu, das ist eine darstellungs-sache vom paging und sollte auch da konfiguriert werden

2020-09-16 15:52 UTC, nsams commented on packages/react-admin-core/src/table/Pagination.tsx
> +                                        if (Math.abs(parseInt(values.page) - parseInt(e.target.value)) === 1) {
das bedarf einer erklärung :)

2020-09-16 15:52 UTC, nsams commented on packages/react-admin-core/src/table/Pagination.tsx
> +        fetchSpecificPage && fetchSpecificPage(values.page);
mach ganz oben in der component if (!fetchSpecificPage) return null; Oder, noch besser mach es pflicht in der props dann brauchst du da nicht prüfen

2020-09-23 09:03 UTC, jamesricky requested changes

2020-09-23 09:03 UTC, jamesricky commented on packages/react-admin-core/src/table/Pagination.sc.ts
> +export const Button = styled(ButtonBase)`
Der Button wird garnicht verwendet oder?

2020-09-23 09:08 UTC, jamesricky commented on packages/react-admin-core/src/table/paging/createRestPagingActions.ts
> +    options: IOptions = { pageParameterName: "page", firstLastPage: false, specificPage: false, hideTotalCount: false },
Macht's vielleicht Sinn `firstLastPage` standardmäßig auf `true` zu setzen?   
Oder vielleicht gar kein Prop machen und die Buttons immer anzeigen, mir fällt kein Fall ein, wo wir das nicht haben wollen...

@nsams @kaufmo @rabengraph  was meint ihr?

2021-01-12 13:39 UTC, closed without merging